apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapRoles: |
    - rolearn: {{ .Values.roleArn }}
      username: system:node:{{ "{{" }}EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
