apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 3.4.0
  name: prometheus-k8s
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - interval: 10s
    port: gandalf
  - interval: 10s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
