apiVersion: v1
kind: Service
metadata:
  name: gandalf-svc
  namespace: default
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # Uncomment for internal load balancer
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: gandalf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
