name: Deploy Charts

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.0' 

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name main

      - name: Check pwd
        run: |
          pwd
          ls
      - name: Deploy aws-config
        run: helm upgrade --install aws-config charts/aws-config

      - name: Add helm charts
        run: |
          helm version
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Deploy ingress
        run: |
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx --create-namespace \
          --set controller.service.enabled=false
          --set controller.metrics.enabled=true \
          --set controller.metrics.serviceMonitor.enabled=true \
          --set controller.metrics.serviceMonitor.namespace=monitoring \
          --set controller.metrics.serviceMonitor.interval=30s \
          --set controller.metrics.serviceMonitor.scrapeTimeout=10s
          helm upgrade --install charts/ingress

      - name: Deploy node-exporter
        run: helm upgrade --install node-exporter prometheus-community/prometheus-node-exporter

      - name: Deploy Gandalf app
        run: helm upgrade --install app charts/gandalf-app

